services:
  postgres:
    image: postgres:15
    container_name: async_postgres
    env_file:
      - ./private/private.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
